#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
# config/routes.yaml
app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
  
app_lucky_number:
  path: /UploadFile
  controller: App\Controller\UploadFileController::number
api_login_check:
  path: /api/login
api_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

  